warning_threshold: 15

excluded:
 - Pods
 - MBUITest

opt_in_rules:
- private_outlet
- private_action

disabled_rules:
 - trailing_whitespace
 - force_cast
 - identifier_name

line_length: 150
warning: 150

function_parameter_count:
warning: 10
error: 15

file_length:
warning: 500

type_body_length:
warning: 400
error: 450
