warning_threshold: 15

excluded:
 - Pods

opt_in_rules:
- private_outlet
- private_action
- attributes
- closure_spacing
- multiline_arguments
- multiline_function_chains
- operator_usage_whitespace
- single_test_class
- vertical_parameter_alignment
- vertical_parameter_alignment_on_call    

disabled_rules:
 - trailing_whitespace
 - force_cast
 - identifier_name
 - switch_case_alignment

line_length: 150
warning: 150

function_parameter_count:
    warning: 10
    error: 15

file_length:
    warning: 500

type_body_length:
    warning: 400
    error: 450
