language: swift
osx_image: xcode9.4

before_install:
- export IOS_SIMULATOR_UDID=`instruments -s devices | grep "iPhone 8 (11.4" | awk -F '[ ]' '{print $4}' | awk -F '[\[]' '{print $2}' | sed 's/.$//'`
- echo $IOS_SIMULATOR_UDID
- open -a "simulator" --args -CurrentDeviceUDID $IOS_SIMULATOR_UDID

script:
- xcodebuild -workspace ITEvents.xcworkspace -scheme ITEvents -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.4' build test
