{\rtf1\ansi\ansicpg1252\cocoartf1561\cocoasubrtf400
{\fonttbl\f0\fnil\fcharset0 Menlo-Regular;}
{\colortbl;\red255\green255\blue255;\red0\green0\blue0;\red0\green0\blue0;\red0\green0\blue0;
\red0\green0\blue0;}
{\*\expandedcolortbl;;\cssrgb\c0\c0\c0\c84314;\cssrgb\c0\c0\c0\c4706;\cssrgb\c0\c0\c0\c84314;
\cssrgb\c0\c0\c0\c4706;}
\paperw11900\paperh16840\margl1440\margr1440\vieww10800\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\sl380\partightenfactor0

\f0\fs32 \cf2 \cb3 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec2 language: swift\cb1 \
\cb3 osx_image: xcode10.0\cb1 \
\cb3 script:\cb1 \
\cb3     - xcodebuild clean test -project ITEvents.xcworkspace -scheme \cf4 \cb5 \outl0\strokewidth0 ITEvents\cf2 \cb3 \outl0\strokewidth0 \strokec2  -destination "platform=iOS Simulator,name=iPhone 8,OS=12.0\'94 CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet\
}