language: swift
osx_image: xcode10
env:
    global:
        - WORKSPACE=ITEvents.xcworkspace
    matrix:
        - SCHEME="ITEvents"
          SIMULATOR="platform=iOS Simulator,OS=12.0,name=iPhone 8"

# Build Framework in Debug and Run Tests if specified
script:
    - xcodebuild -workspace $WORKSPACE -scheme "$SCHEME" test -destination "$SIMULATOR"
