language: swift
osx_image: xcode9.4
env:
    global:
        - WORKSPACE=ITEvents.xcworkspace
    matrix:
        - SCHEME="ITEvents"
          SDK=iphonesimulator11.4
          SIMULATOR="platform=iOS Simulator,OS=11.4,name=iPhone 8"

# Build Framework in Debug and Run Tests if specified
script:
    - travis_retry xcodebuild -workspace $WORKSPACE -scheme "$SCHEME" -sdk $SDK test -destination "$SIMULATOR" | xcpretty -c
