language: swift
osx_image: xcode9.4
script:
- xcodebuild clean test -workspace ITEvents.xcworkspace -scheme ITEvents -destination "platform=iOS Simulator,name=iPhone 8,OS=11.4” CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet
