language: swift
osx_image: xcode10.0
script:
- xcodebuild clean test -project ITEvents.xcworkspace -scheme ITEvents -destination "platform=iOS Simulator,name=iPhone 8,OS=12.0” CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet
